name: Build Test and Deploy

on: 
  push:
    branches:
      - main
env:
  PROJECT_VERSION: 1.0.0

jobs:
  main_job:
    runs-on: ubuntu-latest # Définit l'environnement d'exécution
    steps:
      - name: Récupération du code source
        run: cd ../..
      - name: Récupération du code source
        run : mvn clean package -DskipTests 
        
    
