name: Build Test and Deploy

on: 
  push:
    branches:
      - main
      - master

env:
  PROJECT_VERSION: 1.0.0

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérification et récupération du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuration de la version du projet
      - name: Afficher la version du projet
        run: echo "PROJECT_VERSION=${{ env.PROJECT_VERSION }}"

      # Construction du projet
      - name: Build project
        run: mvn clean package -DskipTests

   

        
    
